### ISSUE TITLE
Unable to use globally inherited CredentialPath in CAPI creation

### ISSUE THREAD

**Issue by ferneaux** [gdbarron/VenafiTppPS#83] opened 2019-09-17 19:31 UTC
So I'm part of a team that has access to the API in our Venafi (v18.4.0.3063) environment, but we are not Master Admins. I'm running into a problem with the CredentialPath parameter of the New-TppCapiApplication function. I'm unable to use the global credentials set by the Admins because it says that the object doesn't exist... more specifically "Credential object not found". I can see the cred path when creating CAPI's via the web interface, so I know it is correct. I suspect that this is because of my access rights, so I was wondering if there was a workaround or a way to toss something like an "IsInherited" switch in there. Any ideas or help would be most appreciated.

**Comment by gdbarron** [comment] 2019-09-18 02:19
Hi @ferneaux.  When a credential is provided, I'm performing validation to ensure it exists before creating the capi object.  That validation tries to retrieve the object details which is where you are most likely getting blocked.  Can you run the command with -verbose and paste the results here so I can confirm where the issue is?  I'll look to add something to allow bypassing the existence check.  Thanks.

**Comment by ferneaux** [comment] 2019-09-18 13:48
**Thanks for looking at this, Greg. Here is the command I use and the verbose output:**
_(sorry for the odd formatting)_
### New-TppCapiApplication -Path "\VED\Policy\myTeamName\Devices and Applications\server001\test.capi.com" -FriendlyName "test.capi.com - Venafi Managed" -CertificatePath "\VED\Policy\myTeamName\Webserver\test.myDomainName.com" -CredentialPath "\VED\Policy\_Administration\Access Credential Certificates\AD Credentials\myDomainName-dirpla05" -Verbose
VERBOSE: ValidUntil: 9/18/2019 1:24:16 PM, Current (+2s): 9/18/2019 1:21:56 PM
VERBOSE: ValidUntil: 9/18/2019 1:24:16 PM, Current (+2s): 9/18/2019 1:21:56 PM
VERBOSE: {
    "ContentType":  "application/json",
    "Method":  "Post",
    "Body":  "{\r\n    \"ObjectDN\":  \"\\\\VED\\\\Policy\\\\myTeamName\\\\Webserver\\\\test.myDomainName.com\"\r\n}",
    "Headers":  {
                    "X-Venafi-Api-Key":  "b1257ce4-06dc-1b11-9400-7f1374b0283a"
                },
    "Uri":  "https://venafi.myDomainName.com/vedsdk/config/IsValid"
}
VERBOSE: POST https://venafi.myDomainName.com/vedsdk/config/IsValid with -1-byte payload
VERBOSE: received 541-byte response of content type application/json; charset=utf-8
VERBOSE: ValidUntil: 9/18/2019 1:24:16 PM, Current (+2s): 9/18/2019 1:21:56 PM
VERBOSE: FindByPath
VERBOSE: {
    "ContentType":  "application/json",
    "Method":  "Post",
    "Body":  "{\r\n    \"ObjectDN\":  \"\\\\VED\\\\Policy\\\\_Administration\\\\Access Credential Certificates\\\\AD Credentials\",\r\n    \"Pattern\":  \"myDomainName-dirpla05\"\r\n}",
    "Headers":  {
                    "X-Venafi-Api-Key":  "b1257ce4-06dc-1b11-9400-7f1374b0283a"
                },
    "Uri":  "https://venafi.myDomainName.com/vedsdk/config/enumerate"
}
VERBOSE: POST https://venafi.myDomainName.com/vedsdk/config/enumerate with -1-byte payload
VERBOSE: received 25-byte response of content type application/json; charset=utf-8
Credential object not found
At C:\Users\myUserName\Documents\WindowsPowerShell\Modules\VenafiTppPS\1.1.0\Public\New-TppCapiApplication.ps1:163 char:9
+         throw "Credential object not found"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Credential object not found:String) [], RuntimeException
    + FullyQualifiedErrorId : Credential object not found

**The web interface actually lists the credential as "\Policy\_Administration\Access Credential Certificates\AD Credentials\myDomainName-dirpla05", but if I use that, I immediately get the error:**

New-TppCapiApplication : Cannot validate argument on parameter 'CredentialPath'. '\Policy\_Administration\Access Credential Certificates\AD Credentials\myDomainName-dirpla05' is not a valid DN path
At line:1 char:285
+ ... dentialPath "\Policy\_Administration\Access Credential Certificates\A ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-TppCapiApplication], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,New-TppCapiApplication


Hope that helps!

Thanks,
Mark

**Comment by gdbarron** [comment] 2019-09-18 20:29
Thanks for the info, Mark, it does help :)  The first error, Credential object not found, is due to trying to retrieve an object you don't have access to.  I've [updated the New-TppCapiApplication function](https://github.com/gdbarron/VenafiTppPS/blob/non-mandatory-cred-path/VenafiTppPS/Code/Public/New-TppCapiApplication.ps1) with 2 sets of changes.  First, I've made credential and certificate non-mandatory so you can choose to provide them or not.  Also, I've added a new parameter `-SkipExistenceCheck` which will bypass the following checks:

- ensure an object exists at the parent path provided for $Path and it is of type Device
- ensure the certificate path exists and is an actual certificate
- ensure the credential path exists and has 'credential' in the type name (the latter part of this isn't the best and working on making it more definitive)

The second error, not a valid DN path, is due to the credential path not starting with \ved as in your first command.  If the path truly does not start with \ved, this will be the first time I am hearing it and will have to rethink path validation.  I hope it's just that you're not seeing \ved for some reason.

Are you able to take the updated code and ensure it works for you before I commit?  I would try with and without \ved just to cover all bases.

**Comment by ferneaux** [comment] 2019-09-19 12:44
I'll be testing this shortly and rigorously.... I'll let you know how it goes. THANKS for the fast response.

**Comment by ferneaux** [comment] 2019-09-19 13:50
ok... so here's what I found...

- Omitting "\VED\" fails every time with the "...is not a valid DN path" error as mentioned in previous post. I even tried omitting it for both CertificatePath and CredentialPath parameters.
- Omitting the CertificatePath and CredentialPath parameters allows me to create the CAPI. It populates the inherited CredentialPath and leaves the associated cert blank.
- Providing the CertificatePath fails with error stating the object cannot be found. Verbose info on that error below.
- Providing the CertificatePath AND including the SkipExistenceCheck creates the CAPI as desired.

Here is the error I get (_again, sorry for the formatting LOL_):
### New-TppCapiApplication -Path "\VED\Policy\myTeamName\Devices and Applications\server001\test.capi.com" -FriendlyName "test.capi.com - Venafi Managed" -CertificatePath "\VED\Policy\myTeamName\Webserver\test.myDomainName.com" -Verbose
VERBOSE: ValidUntil: 9/19/2019 1:12:53 PM, Current (+2s): 9/19/2019 1:16:23 PM
VERBOSE: GET https://venafi.myDomainName.com/vedsdk/authorize/checkvalid with 0-byte payload
VERBOSE: received 88-byte response of content type application/json; charset=utf-8
VERBOSE: ValidUntil: 9/19/2019 1:12:53 PM, Current (+2s): 9/19/2019 1:16:23 PM
VERBOSE: GET https://venafi.myDomainName.com/vedsdk/authorize/checkvalid with 0-byte payload
VERBOSE: received 88-byte response of content type application/json; charset=utf-8
VERBOSE: {
    "ContentType":  "application/json",
    "Method":  "Post",
    "Body":  "{\r\n    \"Pattern\":  \"server001\",\r\n    \"ObjectDN\":  \"\\\\VED\\\\Policy\\\\myTeamName\\\\Devices and Applications\"\r\n}",
    "Headers":  {
                    "X-Venafi-Api-Key":  "c73cb3c7-3f96-bf5a-4014-fd3c7b9dbd12"
                },
    "Uri":  "https://venafi.myDomainName.com/vedsdk/config/enumerate"
}
VERBOSE: POST https://venafi.myDomainName.com/vedsdk/config/enumerate with -1-byte payload
VERBOSE: received 546-byte response of content type application/json; charset=utf-8
VERBOSE: ValidUntil: 9/19/2019 1:12:53 PM, Current (+2s): 9/19/2019 1:16:24 PM
VERBOSE: GET https://venafi.myDomainName.com/vedsdk/authorize/checkvalid with 0-byte payload
VERBOSE: received 88-byte response of content type application/json; charset=utf-8
VERBOSE: {
    "ContentType":  "application/json",
    "Method":  "Get",
    "Body":  {
                 "ParentDn":  "\\VED\\Policy\\myTeamName\\Webserver"
             },
    "Headers":  {
                    "X-Venafi-Api-Key":  "c73cb3c7-3f96-bf5a-4014-fd3c7b9dbd12"
                },
    "Uri":  "https://venafi.myDomainName.com/vedsdk/certificates"
}
VERBOSE: GET https://venafi.myDomainName.com/vedsdk/certificates?ParentDn=\VED\Policy\myTeamName\Webserver with 0-byte payload
VERBOSE: received 73474-byte response of content type application/json; charset=utf-8
A certificate object could not be found at '\VED\Policy\myTeamName\Webserver\test.myDomainName.com'
At C:\Users\myUserName\Documents\WindowsPowerShell\Modules\VenafiTppPS\1.1.0\Public\New-TppCapiApplication.ps1:183 char:17
+ ...             throw ('A certificate object could not be found at ''{0}' ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (A certificate o...r\test.myDomainName.com':String) [], RuntimeException
    + FullyQualifiedErrorId : A certificate object could not be found at '\VED\Policy\myTeamName\Webserver\test.myDomainName.com'

**Comment by gdbarron** [comment] 2019-09-20 00:07
Thanks for the testing, it sounds as if we're on the right track.  Please see my comments inline:

- Omitting "\VED" fails every time with the "...is not a valid DN path" error as mentioned in previous post. I even tried omitting it for both CertificatePath and CredentialPath parameters.
    - This is expected given the current path validation.  Did you confirm if the credential path starts with \ved or not by creating a capi app with a credential path and `-SkipExistenceCheck`?
- Omitting the CertificatePath and CredentialPath parameters allows me to create the CAPI. It populates the inherited CredentialPath and leaves the associated cert blank.
    - Perfect
- Providing the CertificatePath fails with error stating the object cannot be found. Verbose info on that error below.
    - In addition to not having access to Credentials, do you not have access to Certificates either?  It sounds as if this is the case given the next test, but want to be sure.
- Providing the CertificatePath AND including the SkipExistenceCheck creates the CAPI as desired.
    - Perfect

**Comment by ferneaux** [comment] 2019-09-23 12:53
Sorry for the delay... work getting in the way of "progress". LOL

To answer your questions:

- _**Did you confirm if the credential path starts with \ved or not by creating a capi app with a credential path and `-SkipExistenceCheck`?**_
Yes, it does begin with \ved. If I included it, the CAPI would be created, but ONLY if I included the new `-SkipExistenceCheck` parameter. If I did not include \ved, even with the SKIP parameter, it would fail stating that the DN Path was not valid.

- _**In addition to not having access to Credentials, do you not have access to Certificates either?**_
Yes, I do have access to that cert. I created it exclusively for these tests. I did not rec'v an error when using the SKIP parameter.


Thanks!
Mark

**Comment by gdbarron** [comment] 2019-10-11 20:51
Hi @ferneaux, just checking in on this.  Are we good to close this one?  Thanks!

**Comment by gdbarron** [comment] 2020-05-05 17:43
Going through old issues, @ferneaux, this good?

**Comment by ferneaux** [comment] 2020-05-07 03:36
> Going through old issues, @ferneaux, this good?

Yup, this was resolved. Thanks for all the work! Much appreciated!

**Closed** 2020-05-07 12:29 UTC
